## EEP 596 Conceptual Assignment 1
### Qingchuan Hou

### Problem 1

#### 1.1 Hand Computation
$
X = \begin{bmatrix}
4 & -3 \\
-2 & 5 
\end{bmatrix} 
$

**(1)** $
X_T = \begin{bmatrix}
4 & -2 \\
-3 & 5 
\end{bmatrix} 
$

**(2)** $Tr(X) = x_{11} + x_{22} = 4 + 5 = 9$


**(3)** $||X||_F$
$$
\begin{align*}
||X||_F & = \sqrt{Tr(X^T X)} \\
        & = \sqrt{Tr(\begin{bmatrix}
                    4 & -2 \\
                    -3 & 5 
                    \end{bmatrix}  
                    \begin{bmatrix}
                    4 & -3 \\
                    -2 & 5 
                    \end{bmatrix} )} \\
        & = \sqrt{Tr(\begin{bmatrix}
                    4^2+(-2)^2 & 4*(-3)+5*(-2) \\
                    -3*4+5*(-2) & (-3)^2 + 5^2
                    \end{bmatrix} )} \\
        & = \sqrt{Tr(\begin{bmatrix}
                    20 & -22 \\
                    -22 & 34 
                    \end{bmatrix} )} \\
        & = \sqrt{20+34} \\
        & = \sqrt{54} \\
        & \approx 7.3
\end{align*}
$$

**(4)** $2 \times X = 
\begin{bmatrix}
2*4 & 2*(-3) \\
2*(-2) & 2*5 
\end{bmatrix} =
\begin{bmatrix}
8 & -6 \\
-4 & 10 
\end{bmatrix} $

**(5)** 
$ X + I = \begin{bmatrix}
4 & -3 \\
-2 & 5 
\end{bmatrix} +
\begin{bmatrix}
1 & 0 \\
0 & 1 
\end{bmatrix} =
\begin{bmatrix}
5 & -3 \\
-2 & 6 
\end{bmatrix} 
$



#### 1.2 Python Verify

In [1]:
import numpy as np

In [2]:
X = np.array([[4, -3], [-2, 5]])

In [3]:
print('X.T:',X.T)
print('\nTrace of X:', X.trace())
print('\nFrobenius Norm of X:', np.linalg.norm(X))
print('\n2 x X:', 2*X)

I = np.eye(X.shape[0], X.shape[1])
print('\nX + I:', X+I)


X.T: [[ 4 -2]
 [-3  5]]

Trace of X: 9

Frobenius Norm of X: 7.3484692283495345

2 x X: [[ 8 -6]
 [-4 10]]

X + I: [[ 5. -3.]
 [-2.  6.]]


### Problem 2


#### 2.1 Hand Compute
$ X - I = \begin{bmatrix}
4 & -3 \\
-2 & 5 
\end{bmatrix} -
\begin{bmatrix}
1 & 0 \\
0 & 1 
\end{bmatrix} =
\begin{bmatrix}
3 & -3 \\
-2 & 4 
\end{bmatrix}, \ \ \ \ 
(X-I)^T = \begin{bmatrix}
3 & -2 \\
-3 & 4 
\end{bmatrix}, 
$

$$
\begin{align*}
||X-I||_F & = \sqrt{Tr((X-I)^T (X-I))} \\
        & = \sqrt{Tr(\begin{bmatrix}
                    3 & -2 \\
                    -3 & 4 
                    \end{bmatrix}  
                    \begin{bmatrix}
                    3 & -3 \\
                    -2 & 4 
                    \end{bmatrix} )} \\
        & = \sqrt{Tr(\begin{bmatrix}
                    3^2+(-2)^2 & 3*(-3)+4*(-2) \\
                    -3*3+4*(-2) & (-3)^2 + 4^2
                    \end{bmatrix} )} \\
        & = \sqrt{Tr(\begin{bmatrix}
                    13 & -17 \\
                    -17 & 25 
                    \end{bmatrix} )} \\
        & = \sqrt{13+25} \\
        & = \sqrt{38} \\
        & \approx 6.2
\end{align*}
$$

#### 2.2 Python Verify

In [4]:
Y = X - I
print('Frobenius Norm of X-I:', np.linalg.norm(X-I))


Frobenius Norm of X-I: 6.164414002968976


In [5]:
Y.T.dot(Y)

array([[ 13., -17.],
       [-17.,  25.]])

### Problem 3


In [6]:
Z = np.array([[4, -3, -1], [-2, 5, 2], [8, -6, -1]])

# SVD of Z
u, s, vh = np.linalg.svd(Z, full_matrices=False)
u, s, vh

(array([[-0.41222084, -0.12359436, -0.90266185],
        [ 0.41537654, -0.90729099, -0.06546285],
        [-0.81088613, -0.4019297 ,  0.42534245]]),
 array([12.30911408,  2.88624728,  0.39406485]),
 array([[-0.72846229,  0.66445578,  0.16685685],
        [-0.65664265, -0.60774199, -0.44662075],
        [-0.19535382, -0.4349117 ,  0.87902713]]))

In [7]:
# Rank-2 approximation of Z
u_2 = u[:,:2]
s_2 = np.diag(s[:2])
vh_2 = vh[:2,:]

Z_2 = u_2.dot(s_2).dot(vh_2)
Z_2

array([[ 3.93051122, -3.15470127, -0.68732362],
       [-2.00503947,  4.98878075,  2.02267592],
       [ 8.03274374, -5.92710336, -1.14733594]])

In [8]:
error = np.linalg.norm(Z - Z_2) / np.linalg.norm(Z)
print("The relative error:", error)

The relative error: 0.031153562088046625


The magnitude of the error make sense. The matrix Z_2 is the rank-2 approximation of Z by using the truncated SVD. It reduce the size but keeps the main information. Therefore, the matrix Z_2 should be similar to the matrix Z. That's why the relative error is small. 

The truncated SVD is the sparse mode of full SVD, it keeps the primary information of the data matrix and reduces the size of the matrix. In machine learning, the data matrix is always huge and will cost a lot of memory and computation to calculate the matrix. Because the truncated SVD can be much smaller than the full SVD, it will reduce the use of memory and computation costs.

### Problem 4 - 8

4. B
5. D
6. A, B, C, D
7. C
8. D