In [12]:
import numpy as np
a = [a for a in np.arange(3)]
a


[0, 1, 2]

In [2]:
from math import *
import numpy as np
from scipy.linalg import lu_factor, lu_solve
from scipy.linalg import qr, solve_triangular

In [10]:
enrollemt = np.array([39896, 40434, 41294, 42023, 42355, 43035, 43859, 43617, 44157, 44939])

enrollemt_diff = []

for i in range(len(enrollemt)-1):
    enrollemt_diff.append(enrollemt[i+1] - enrollemt[i])

print('Enrollment change each year:',enrollemt_diff)

np.gradient(enrollemt_diff, varargs=1)

SyntaxError: invalid syntax (985605389.py, line 10)

In [ ]:
vmat = np.array([[1,1,1,1,1], [0,1,2,3,4], [0,1,4,9,16],[0,1,8,27,64],[0,1,16,81,256]])

In [37]:
import torch

a = torch.rand((5,3), requires_grad=True)
c = torch.rand((3,10), requires_grad=True)
d = torch.rand((5,10))
b = torch.matmul(a,c) - d
print(a, b)
torch.sum(torch.pow(b, 2)).backward()
a, a.grad,c, c.grad

# torch.sum(b),torch.mean(b)


tensor([[0.1434, 0.0755, 0.0325],
        [0.8175, 0.9428, 0.9265],
        [0.5726, 0.4585, 0.3667],
        [0.5515, 0.6069, 0.3442],
        [0.1329, 0.6872, 0.4325]], requires_grad=True) tensor([[-0.3078, -0.0509, -0.5352, -0.1471, -0.8418, -0.2045, -0.0681, -0.7373,
         -0.6520, -0.0130],
        [ 0.8087,  0.7139,  1.1394,  1.4977, -0.1948,  0.5544,  1.8764,  1.0141,
          0.6360,  1.1029],
        [-0.0616,  0.2335, -0.1861,  0.3593, -0.4036,  0.3157,  0.8308, -0.1285,
          0.6561,  0.5494],
        [ 0.0816, -0.1369, -0.1324,  0.6796, -0.3780,  0.0200,  1.3905,  0.8364,
          0.2325,  0.5091],
        [ 0.2381,  0.0512,  0.4298,  0.2060, -0.1892,  0.2719,  0.8697,  0.2722,
         -0.0128,  0.1052]], grad_fn=<SubBackward0>)


(tensor([[0.1434, 0.0755, 0.0325],
         [0.8175, 0.9428, 0.9265],
         [0.5726, 0.4585, 0.3667],
         [0.5515, 0.6069, 0.3442],
         [0.1329, 0.6872, 0.4325]], requires_grad=True),
 tensor([[-1.7763, -3.9981, -3.8859],
         [ 9.4915, 14.5071, 10.6797],
         [ 3.1194,  3.6353,  2.7947],
         [ 5.0529,  6.0803,  4.2629],
         [ 2.7305,  3.6761,  3.3175]]),
 tensor([[0.5177, 0.1725, 0.0372, 0.7000, 0.0067, 0.1933, 0.9965, 0.3880, 0.2937,
          0.5053],
         [0.7663, 0.9732, 0.4779, 0.7982, 0.2555, 0.3200, 0.9644, 0.9804, 0.3980,
          0.9199],
         [0.4984, 0.1245, 0.9994, 0.2902, 0.1297, 0.2999, 0.9609, 0.5170, 0.8983,
          0.2130]], requires_grad=True),
 tensor([[ 1.3167,  1.2826,  1.4644,  3.6223, -1.4895,  1.3036,  5.7646,  2.2942,
           1.8573,  3.0181],
         [ 1.8483,  1.4567,  2.3270,  4.2392, -1.5834,  1.7019,  7.1727,  3.0724,
           1.9671,  3.3438],
         [ 1.6955,  1.4409,  2.2207,  3.6751, -1.1356,  1.4945, 